apiVersion: v2
name: pagopa-afm-marketplace
description: Microservice that handles marketplace for pagoPA Advanced Fees Management
type: application
version: 0.111.0
appVersion: 0.21.19-1-PIDM-863-paymenttypes-touchpoint-any
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
